name: plant-model
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - aom=3.5.0
  - attr=2.5.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - blosc=1.21.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - c-blosc2=2.9.2
  - cairo=1.16.0
  - cfitsio=4.2.0
  - charls=2.4.2
  - charset-normalizer=3.1.0
  - click=8.1.3
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - contourpy=1.0.7
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2023.5.1
  - dav1d=1.2.1
  - dbus=1.13.6
  - expat=2.5.0
  - ffmpeg=4.3
  - fftw=3.3.10
  - filelock=3.12.0
  - fontconfig=2.14.2
  - fonttools=4.39.4
  - freetype=2.12.1
  - fsspec=2023.5.0
  - ftfy=6.1.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.76.3
  - glib-tools=2.76.3
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - graphite2=1.3.13
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.34
  - harfbuzz=6.0.0
  - huggingface_hub=0.15.1
  - icu=70.1
  - idna=3.4
  - imageio=2.28.1
  - jack=1.9.22
  - jinja2=3.1.2
  - joblib==1.2.0
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.2
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpg123=1.31.3
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nettle=3.6
  - networkx=3.1
  - nspr=4.35
  - nss=3.89
  - numpy=1.24.3
  - openh264=2.1.1
  - openjpeg=2.5.0
  - packaging=23.1
  - pandas=2.0.1
  - partd=1.4.0
  - pcre2=10.40
  - pillow=9.5.0
  - pip=23.1.2
  - pixman=0.40.0
  - ply=3.11
  - pthread-stubs=0.4
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2023.3
  - pywavelets=1.4.1
  - pyyaml=6.0
  - qt-main=5.15.8
  - readline=8.2
  - regex=2023.5.5
  - requests=2.31.0
  - safetensors=0.3.1
  - scikit-image=0.20.0
  - scikit-learn==0.24.1
  - scipy=1.9.1
  - setuptools=67.7.2
  - sip=6.7.9
  - six=1.16.0
  - snappy=1.1.10
  - sympy=1.12
  - timm=0.6.13
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - torchtriton=2.0.0
  - torchvision=0.15.1
  - tornado=6.3.2
  - tqdm=4.65.0
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzdata=2023c
  - unicodedata2=15.0.0
  - urllib3=2.0.2
  - wcwidth=0.2.6
  - xz=5.2.6
  - yaml=0.2.5
  - zfp=1.0.0
  - zipp=3.15.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.2
  - pip:
      - datatable==1.0.0
